extent.reporter.spark.start=true
extent.reporter.spark.out=reports/extent-report.html
extent.reporter.spark.config=extent-config.xml
extent.reporter.spark.vieworder=dashboard,test,category,exception,author,device,log
extent.reporter.pdf.start=true
extent.reporter.pdf.out=reports/ExtentPdf.pdf
systeminfo.os=Windows/Linux
systeminfo.user=OpenAI ChatGPT
systeminfo.build=1.0-SNAPSHOT
