baseURL=https://reqres.in
getUserEndpoint=/api/users/{{userId}}
getUserListEndpoint=/api/users/?page=2
getProductListEndpoint=/api/products?page=1
userRegisterEndpoint=/api/register
userLoginEndpoint=/api/login
deleteUserEndpoint=/api/users/2
apiKey=reqres_a341fcb70a704ca6a29ee1a42ddf72ad
excelPath=src/test/resources/testdata/data.xlsx
defaultSheet=Users